import React from "react";
import { Inter } from "next/font/google";
import StyledComponentsRegistry from "../lib/AntdRegistry";
import "./globals.css";
import Skeleton from "./components/Skeleton";
import { ConfigProvider, theme } from "antd";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => (
  <html lang="en">
    <ConfigProvider
      theme={{
        token: {
          fontFamily: inter.style.fontFamily,
        },
        algorithm: theme.defaultAlgorithm,
      }}
    >
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <Skeleton>{children}</Skeleton>
        </StyledComponentsRegistry>
      </body>
    </ConfigProvider>
  </html>
);

export default RootLayout;
